### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by manastyretskyi** [loqimean/tailwindcss_merger#2]
In case `app/assets/stylesheets/application.tailwind.css` is added to `.gitignore`, Heroku is unable to build applications because file is missing, I think we should prepare `application.tailwind.css` before compilation when running `assets:precompile`

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/43040379/163824488-99d3cbb4-0b65-404e-ac79-bad594ea4c60.png">

**Comment by loqimean** [comment]
> In case `app/assets/stylesheets/application.tailwind.css` is added to `.gitignore`, Heroku is unable to build applications because file is missing, I think we should prepare `application.tailwind.css` before compilation when running `assets:precompile`
> 
> <img alt="image" width="1283" src="https://user-images.githubusercontent.com/43040379/163824488-99d3cbb4-0b65-404e-ac79-bad594ea4c60.png">

now it is resolved in version 0.2.1 👌
